version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apollo-server-core
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
    - 2.22.2
  - dependency-name: apollo-server-express
    versions:
    - 2.19.2
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
    - 2.22.2
  - dependency-name: "@graphql-codegen/typescript-react-apollo"
    versions:
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@graphql-codegen/typescript-operations"
    versions:
    - 1.17.14
    - 1.17.15
  - dependency-name: "@graphql-codegen/typescript"
    versions:
    - 1.20.2
    - 1.21.0
    - 1.21.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
