version: '3'
services:
    db:
        image: postgres:12.0
        ports:
            - '5432:5432'
        restart: always
        environment:
            POSTGRES_USER: my_app
            POSTGRES_PASSWORD: my_app_secret
            POSTGRES_DB: my_app
