version: '3'
services:
    db:
        image: postgres:12.0
        ports:
            - '5432:5432'
        restart: always
        environment:
            POSTGRES_PASSWORD: develop
        volumes:
            - './todo-db.sql:/docker-entrypoint-initdb.d/todo-db.sql:ro'
