name: Test code

on: [push]

jobs:
    code-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.13
            - name: Install deps
              run: yarn
            - name: Check code style
              run: yarn check-codestyle

    client:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.13
            - name: Install deps
              run: yarn
              working-directory: ./client
            - name: Generate code front end
              working-directory: ./client
              run: yarn generate
            - name: Run tests
              working-directory: ./client
              run: yarn test
              env:
                  CI: true

    server:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:12.0
                env:
                    POSTGRES_USER: my_app
                    POSTGRES_PASSWORD: my_app_secret
                    POSTGRES_DB: my_app
                ports:
                    # will assign a random free host port
                    - 5432/tcp
                # needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v1
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12.2
            - name: Install deps
              working-directory: ./server
              run: yarn
            - name: Generate code
              working-directory: ./server
              run: yarn generate
            - name: Run tests
              working-directory: ./server
              run: yarn test
              env:
                  CI: true
                  DB_HOST: localhost
                  DB_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
